/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MmhubbubTransCheckerUI;

import java.awt.Point;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author honli
 */
public class MmhubbubTransCheckerUI extends javax.swing.JFrame {

    /**
     * Creates new form DmifTransCheckerUI
     */
    public MmhubbubTransCheckerUI() {
        initComponents();
        this.jDataSetIP = new DataSet();
        this.jDataSetSoC = new DataSet();
        this.bIPOpened = false;
        this.bSoCOpened = false;
        this.vIPDataSet  = new Vector();
        this.vSoCDataSet = new Vector();
        
        this.selectedSoCIndex = -1;
        this.selectedIPIndex = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneIP = new javax.swing.JTabbedPane();
        jPanelIP = new javax.swing.JPanel();
        jLabelOutDirIP = new javax.swing.JLabel();
        jLabelScriptIP = new javax.swing.JLabel();
        jTextFieldOutDirIP = new javax.swing.JTextField();
        jTextFieldScriptIP = new javax.swing.JTextField();
        StartIPAnalyze = new javax.swing.JButton();
        jScrollPaneIP = new javax.swing.JScrollPane();
        jTableIP = new javax.swing.JTable();
        jPanelSoC = new javax.swing.JPanel();
        jLabelOutDirSoC = new javax.swing.JLabel();
        jLabelScriptSoC = new javax.swing.JLabel();
        jTextFieldOutDirSoC = new javax.swing.JTextField();
        jTextFieldScriptSoC = new javax.swing.JTextField();
        StartSoCAnalyze = new javax.swing.JButton();
        jScrollPaneSoC = new javax.swing.JScrollPane();
        jTableSoC = new javax.swing.JTable();
        jPanelCompare = new javax.swing.JPanel();
        jScrollPaneCompareSoC = new javax.swing.JScrollPane();
        jTableCompareSoC = new javax.swing.JTable();
        jScrollPaneCompareIP = new javax.swing.JScrollPane();
        jTableCompareIP = new javax.swing.JTable();
        StartIPSoCCompare = new javax.swing.JButton();
        jTextFrameToCompare = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MMHubbubChecker");

        jTabbedPaneIP.setToolTipText("");
        jTabbedPaneIP.setPreferredSize(new java.awt.Dimension(1280, 800));

        jLabelOutDirIP.setText("Output directory of IP");

        jLabelScriptIP.setText("Analyze script of IP");

        StartIPAnalyze.setText("GO");
        StartIPAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartIPAnalyzeActionPerformed(evt);
            }
        });

        jTableIP.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 13)); // NOI18N
        jTableIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableIP.setToolTipText("");
        jTableIP.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableIP.setColumnSelectionAllowed(true);
        jTableIP.setOpaque(false);
        jTableIP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIPMouseClicked(evt);
            }
        });
        jScrollPaneIP.setViewportView(jTableIP);
        jTableIP.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanelIPLayout = new javax.swing.GroupLayout(jPanelIP);
        jPanelIP.setLayout(jPanelIPLayout);
        jPanelIPLayout.setHorizontalGroup(
            jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIPLayout.createSequentialGroup()
                        .addComponent(StartIPAnalyze)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelIPLayout.createSequentialGroup()
                        .addGroup(jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOutDirIP)
                            .addComponent(jLabelScriptIP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOutDirIP, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                            .addComponent(jTextFieldScriptIP)))
                    .addComponent(jScrollPaneIP))
                .addContainerGap())
        );
        jPanelIPLayout.setVerticalGroup(
            jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutDirIP)
                    .addComponent(jTextFieldOutDirIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScriptIP)
                    .addComponent(jTextFieldScriptIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartIPAnalyze)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneIP, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneIP.addTab("IP", jPanelIP);

        jLabelOutDirSoC.setText("Output directory of SoC");

        jLabelScriptSoC.setText("Analyze script of SoC");

        jTextFieldScriptSoC.setToolTipText("");

        StartSoCAnalyze.setText("GO");
        StartSoCAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartSoCAnalyzeActionPerformed(evt);
            }
        });

        jTableSoC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneSoC.setViewportView(jTableSoC);

        javax.swing.GroupLayout jPanelSoCLayout = new javax.swing.GroupLayout(jPanelSoC);
        jPanelSoC.setLayout(jPanelSoCLayout);
        jPanelSoCLayout.setHorizontalGroup(
            jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSoCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSoCLayout.createSequentialGroup()
                        .addGroup(jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelOutDirSoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelScriptSoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOutDirSoC, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                            .addComponent(jTextFieldScriptSoC, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)))
                    .addGroup(jPanelSoCLayout.createSequentialGroup()
                        .addComponent(StartSoCAnalyze)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneSoC))
                .addContainerGap())
        );
        jPanelSoCLayout.setVerticalGroup(
            jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSoCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutDirSoC)
                    .addComponent(jTextFieldOutDirSoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScriptSoC)
                    .addComponent(jTextFieldScriptSoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartSoCAnalyze)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneSoC, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneIP.addTab("SoC", jPanelSoC);

        jTableCompareSoC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCompareSoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCompareSoCMouseClicked(evt);
            }
        });
        jScrollPaneCompareSoC.setViewportView(jTableCompareSoC);

        jTableCompareIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCompareIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCompareIPMouseClicked(evt);
            }
        });
        jScrollPaneCompareIP.setViewportView(jTableCompareIP);

        StartIPSoCCompare.setText("Compare");
        StartIPSoCCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartIPSoCCompareActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Frame to compare");

        javax.swing.GroupLayout jPanelCompareLayout = new javax.swing.GroupLayout(jPanelCompare);
        jPanelCompare.setLayout(jPanelCompareLayout);
        jPanelCompareLayout.setHorizontalGroup(
            jPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCompareSoC)
                    .addComponent(jScrollPaneCompareIP, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                    .addGroup(jPanelCompareLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFrameToCompare, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartIPSoCCompare)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCompareLayout.setVerticalGroup(
            jPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCompareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCompareIP, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCompareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartIPSoCCompare)
                    .addComponent(jTextFrameToCompare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addComponent(jScrollPaneCompareSoC, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneIP.addTab("Compare", jPanelCompare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneIP, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneIP, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIPMouseClicked
        // TODO add your handling code here:
        System.out.println(this.jTableIP.getSelectedRow());
    }//GEN-LAST:event_jTableIPMouseClicked

    private void StartIPAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartIPAnalyzeActionPerformed
        // TODO add your handling code here:

        this.bIPOpened = false;
        //Init table data
        this.jDataSetIP.CleanUp();

        DefaultTableModel jReqTableModel = new DefaultTableModel(this.jDataSetIP.DataSrc, this.jDataSetIP.ColName);
        this.jTableIP.setModel(jReqTableModel);
        this.jTableIP.repaint();
        this.jTableIP.updateUI();

        System.out.println("IP GO button click.");
        String jOutputDirText = jTextFieldOutDirIP.getText();
        String jScriptDirText = jTextFieldScriptIP.getText();

        if (jOutputDirText.isEmpty() || jScriptDirText.isEmpty()){
            JOptionPane.showMessageDialog(null, "Both two text field need to be filled in", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("jOutputDirText: " + jOutputDirText + "\njScriptDirText: " + jScriptDirText);

        String jFileAwinfoTxt = jOutputDirText + System.getProperty("file.separator") + "mmhubbub_fawinfo_monitor.txt";
        if(new File(jFileAwinfoTxt).exists()) {
            System.out.println(jFileAwinfoTxt + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileAwinfoTxt + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jFileWdataTxt = jOutputDirText + System.getProperty("file.separator") + "mmhubbub_fwdata_monitor.txt";
        if(new File(jFileWdataTxt).exists()) {
            System.out.println(jFileWdataTxt + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileWdataTxt + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String jFileBinfoTxt = jOutputDirText + System.getProperty("file.separator") + "mmhubbub_fbinfo_monitor.txt";
        if(new File(jFileBinfoTxt).exists()) {
            System.out.println(jFileBinfoTxt + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileBinfoTxt + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jFileScript = jScriptDirText + System.getProperty("file.separator") + "mmhubbub_wrt_monitor_analyzer.pl";
        if(new File(jFileScript).exists()) {
            System.out.println(jFileScript + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileScript + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String lineToRead;
        try {
            String jCmd = "perl " + jFileScript + " -dir " + jOutputDirText;
            System.out.println(jCmd);
            Process jProc = Runtime.getRuntime().exec(jCmd);
            InputStream inputStream = jProc.getInputStream();
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
            if ((lineToRead = bufferedReader.readLine()) != null) {
                System.out.println(lineToRead);
                if(lineToRead.equals("PASSED")){
                    System.out.println("Script running properly");
                }
                else{
                    System.out.println("Error: " + bufferedReader.toString());
                    JOptionPane.showMessageDialog(null, "Error: " + bufferedReader.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String jOutputPath = jOutputDirText + System.getProperty("file.separator") + "_out.tmp";
        File jReqOutFile = new File(jOutputPath);
        if(jReqOutFile.isFile() && jReqOutFile.exists()){
            InputStreamReader read = null;
            try {
                System.out.println(jOutputPath + " foundddd");
                read = new InputStreamReader(new FileInputStream(jReqOutFile));
                BufferedReader bufferedReader = new BufferedReader(read);
                String lineTxt = null;
                while((lineTxt = bufferedReader.readLine()) != null){
                    String[] strArray = lineTxt.split(" ");
                    if(strArray.length == 11){
                        Vector jReqElement = new Vector();
                        jReqElement.addElement(strArray[0]); //FrameCount
                        jReqElement.addElement(strArray[1]); //awTime 
                        jReqElement.addElement(strArray[2]); //awId
                        jReqElement.addElement(strArray[3]); //awLen
                        jReqElement.addElement(strArray[4]); //awAddr
                        //jReqElement.addElement("0x" + Integer.toHexString(Integer.parseInt(strArray[3]))); //ReqTag
                        jReqElement.addElement(strArray[5]); //bTime
                        jReqElement.addElement(strArray[10]); //DeltaTime
                        jReqElement.addElement(strArray[8]); //Data1
                        jReqElement.addElement(strArray[9]); //Data2

                        this.jDataSetIP.DataSrc.addElement(jReqElement);
                    }
                    else{
                        System.out.println("Error: Data Format mismatch");
                        return ;
                    }
                }   read.close();

                this.jSetTableColWidth(0, 80, jTableIP);
                this.jSetTableColWidth(1, 80, jTableIP);                                
                this.jSetTableColWidth(2, 100, jTableIP);
                this.jSetTableColWidth(3, 100, jTableIP);
                this.jSetTableColWidth(4, 150, jTableIP);
                this.jSetTableColWidth(5, 100, jTableIP);
                this.jSetTableColWidth(6, 80, jTableIP);

                this.jTableIP.repaint();
                this.jTableIP.updateUI();
                this.bIPOpened = true;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    read.close();
                } catch (IOException ex) {
                    Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            System.out.println("Error: " + jOutputPath + " not found");
        }
    }//GEN-LAST:event_StartIPAnalyzeActionPerformed

    private void StartSoCAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartSoCAnalyzeActionPerformed
        // TODO add your handling code here:
        
        this.bSoCOpened = false;
        //Init table data
        this.jDataSetSoC.CleanUp();

        DefaultTableModel jReqTableModel = new DefaultTableModel(this.jDataSetSoC.DataSrc, this.jDataSetSoC.ColName);
        this.jTableSoC.setModel(jReqTableModel);
        this.jTableSoC.repaint();
        this.jTableSoC.updateUI();

        System.out.println("SoC GO button click.");
        String jOutputDirText = jTextFieldOutDirSoC.getText();
        String jScriptDirText = jTextFieldScriptSoC.getText();

        if (jOutputDirText.isEmpty() || jScriptDirText.isEmpty()){
            JOptionPane.showMessageDialog(null, "Both two text field need to be filled in", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("jOutputDirText: " + jOutputDirText + "\njScriptDirText: " + jScriptDirText);

        
        
        String jFileAwinfoTxt = jOutputDirText + System.getProperty("file.separator") + "mmhubbub_fawinfo_monitor.txt";
        if(new File(jFileAwinfoTxt).exists()) {
            System.out.println(jFileAwinfoTxt + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileAwinfoTxt + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jFileWdataTxt = jOutputDirText + System.getProperty("file.separator") + "mmhubbub_fwdata_monitor.txt";
        if(new File(jFileWdataTxt).exists()) {
            System.out.println(jFileWdataTxt + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileWdataTxt + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String jFileBinfoTxt = jOutputDirText + System.getProperty("file.separator") + "mmhubbub_fbinfo_monitor.txt";
        if(new File(jFileBinfoTxt).exists()) {
            System.out.println(jFileBinfoTxt + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileBinfoTxt + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jFileScript = jScriptDirText + System.getProperty("file.separator") + "mmhubbub_wrt_monitor_analyzer.pl";
        if(new File(jFileScript).exists()) {
            System.out.println(jFileScript + " exists");
        }
        else{
            JOptionPane.showMessageDialog(null, jFileScript + " do not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
//        

        String lineToRead;
        try {
            String jCmd = "perl " + jFileScript + " -dir " + jOutputDirText;
            System.out.println(jCmd);
            Process jProc = Runtime.getRuntime().exec(jCmd);
            InputStream inputStream = jProc.getInputStream();
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
            if ((lineToRead = bufferedReader.readLine()) != null) {
                System.out.println(lineToRead);
                if(lineToRead.compareTo("PASSED") == 0){
                    System.out.println("Script running properly");
                }
                else{
                    System.out.println("Error: " + bufferedReader.toString());
                    JOptionPane.showMessageDialog(null, "Error: " + bufferedReader.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (IOException ex) {
        }
        String jOutputPath = jOutputDirText + System.getProperty("file.separator") + "_out.tmp";
        File jReqOutFile = new File(jOutputPath);
        if(jReqOutFile.isFile() && jReqOutFile.exists()){
            InputStreamReader read = null;
            try {
                System.out.println(jOutputPath + " found");
                read = new InputStreamReader(new FileInputStream(jReqOutFile));
                BufferedReader bufferedReader = new BufferedReader(read);
                String lineTxt = null;
                while((lineTxt = bufferedReader.readLine()) != null){
                    String[] strArray = lineTxt.split(" ");
                    if(strArray.length == 11){
                        Vector jReqElement = new Vector();
                        jReqElement.addElement(strArray[0]); //FrameCount
                        jReqElement.addElement(strArray[1]); //awTime 
                        jReqElement.addElement(strArray[2]); //awId
                        jReqElement.addElement(strArray[3]); //awLen
                        jReqElement.addElement(strArray[4]); //awAddr
                        //jReqElement.addElement("0x" + Integer.toHexString(Integer.parseInt(strArray[3]))); //ReqTag
                        jReqElement.addElement(strArray[5]); //bTime
                        jReqElement.addElement(strArray[10]); //DeltaTime
                        jReqElement.addElement(strArray[8]); //Data1
                        jReqElement.addElement(strArray[9]); //Data2
                        

                        this.jDataSetSoC.DataSrc.addElement(jReqElement);
                    }
                    else{
                        System.out.println("Error: Data Format mismatch");
                        return ;
                    }
                }   read.close();

                this.jSetTableColWidth(0, 80, jTableSoC);
                this.jSetTableColWidth(1, 80, jTableSoC);                                
                this.jSetTableColWidth(2, 100, jTableSoC);
                this.jSetTableColWidth(3, 100, jTableSoC);
                this.jSetTableColWidth(4, 150, jTableSoC);
                this.jSetTableColWidth(5, 100, jTableSoC);
                this.jSetTableColWidth(6, 80, jTableSoC);

                this.jTableSoC.repaint();
                this.jTableSoC.updateUI();
                this.bSoCOpened = true;
            } catch (FileNotFoundException ex) {
            } catch (IOException ex) {
            } finally {
                try {
                    read.close();
                } catch (IOException ex) {
                    Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            System.out.println("Error: " + jOutputPath + " not found");
        }
    }//GEN-LAST:event_StartSoCAnalyzeActionPerformed

    private void StartIPSoCCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartIPSoCCompareActionPerformed
        // TODO add your handling code here:
        if(this.bIPOpened && this.bSoCOpened){            
            this.vIPDataSet.clear();
            this.vSoCDataSet.clear();
            
            String sFrameToCompare = this.jTextFrameToCompare.getText();
            
            this.vIPDataSet.addAll(this.jDataSetIP.DataSrc);
            this.vSoCDataSet.addAll(this.jDataSetSoC.DataSrc);
            
            for (int i = 0; i < vIPDataSet.size();) {

                Vector vIPElement = (Vector) vIPDataSet.elementAt(i);
                String vIPFrameCnt = (String) vIPElement.elementAt(0);
                //System.out.println(sFrameToCompare+" "+vIPFrameCnt+" "+vIPDataSet.size());
                if (!sFrameToCompare.equals(vIPFrameCnt)) {
                    //System.out.println(sFrameToCompare+" "+vIPFrameCnt+" "+vIPDataSet.size());
                    vIPDataSet.remove(i);
                    continue;

                    //skip line which FrameCnt mismatch
                }
                i++;
            }

            for (int i = 0; i < vSoCDataSet.size();) {

                Vector vSoCElement = (Vector) vSoCDataSet.elementAt(i);
                String vSoCFrameCnt = (String) vSoCElement.elementAt(0);
                if (!sFrameToCompare.equals(vSoCFrameCnt)) {
                    //System.out.println(FrameToCompare+" "+vSoCFrameCnt+" "+vSoCDataSet.size());
                    vSoCDataSet.remove(i);
                    continue;

                    //skip line which FrameCnt mismatch
                }
                i++;
            }
             
            for (int i = 0; i < vIPDataSet.size(); ){
                boolean bFound = false;
                
                Vector vIPElement = (Vector) vIPDataSet.elementAt(i);
                String vIPFrameCnt = (String) vIPElement.elementAt(0);
                
                
                String vIPTag = (String) vIPElement.elementAt(4);
                String vIPData1 = (String) vIPElement.elementAt(7);
                String vIPData2 = (String) vIPElement.elementAt(8);
                for (int j = 0; j < vSoCDataSet.size();){                    
                    Vector vSoCElement = (Vector) vSoCDataSet.elementAt(j);
                    String vSoCFrameCnt = (String) vSoCElement.elementAt(0);
                    String vSoCTag = (String) vSoCElement.elementAt(4);
                    String vSoCData1 = (String) vSoCElement.elementAt(7);
                    String vSoCData2 = (String) vSoCElement.elementAt(8);
                    
                    if( vIPFrameCnt.equals(vSoCFrameCnt) && vIPTag.equals(vSoCTag) && vIPData1.equals(vSoCData1) && vIPData2.equals(vSoCData2)){                        
                        vSoCDataSet.remove(j);
                        bFound = true;
                        break;
                    }
                    else{
                        j++;
                    }                    
                }
                if(bFound){
                    vIPDataSet.remove(i);
                    continue;
                }
                else{
                    i++;
                }
            }            
            DefaultTableModel jOutIPTableModel = new DefaultTableModel(vIPDataSet, this.jDataSetIP.ColName);
            this.jTableCompareIP.setModel(jOutIPTableModel);

                this.jSetTableColWidth(0, 80, jTableCompareIP);
                this.jSetTableColWidth(1, 80, jTableCompareIP);                                
                this.jSetTableColWidth(2, 100, jTableCompareIP);
                this.jSetTableColWidth(3, 100, jTableCompareIP);
                this.jSetTableColWidth(4, 150, jTableCompareIP);
                this.jSetTableColWidth(5, 100, jTableCompareIP);
                this.jSetTableColWidth(6, 80, jTableCompareIP);

            this.jTableCompareIP.repaint();
            this.jTableCompareIP.updateUI();
            
            DefaultTableModel jOutSoCTableModel = new DefaultTableModel(vSoCDataSet, this.jDataSetSoC.ColName);
            this.jTableCompareSoC.setModel(jOutSoCTableModel);

                this.jSetTableColWidth(0, 80, jTableCompareSoC);
                this.jSetTableColWidth(1, 80, jTableCompareSoC);                                
                this.jSetTableColWidth(2, 100, jTableCompareSoC);
                this.jSetTableColWidth(3, 100, jTableCompareSoC);
                this.jSetTableColWidth(4, 150, jTableCompareSoC);
                this.jSetTableColWidth(5, 100, jTableCompareSoC);
                this.jSetTableColWidth(6, 80, jTableCompareSoC);

            this.jTableCompareSoC.repaint();
            this.jTableCompareSoC.updateUI();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Need to open analyze IP and SoC results first", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_StartIPSoCCompareActionPerformed

    private void jTableCompareSoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompareSoCMouseClicked
        // TODO add your handling code here:
        this.selectedSoCIndex = -1;
        System.out.println(this.jTableCompareSoC.getName() + ": " + this.jTableCompareSoC.getSelectedRow() + " has been selected.");
        this.selectedSoCIndex = this.jTableCompareSoC.getSelectedRow();
        System.out.println(this.jTableCompareSoC.getName() + ": " + this.vSoCDataSet.get(selectedSoCIndex));
        if(this.selectedSoCIndex != -1){
            Vector vSelectedEntry = (Vector) this.vSoCDataSet.get(selectedSoCIndex);
            for(int i = 0; i < this.jDataSetSoC.DataSrc.size(); i++){
                Vector vIter = (Vector) this.jDataSetSoC.DataSrc.elementAt(i);
                if (vIter == vSelectedEntry){
                    this.jTableSoC.setRowSelectionInterval(i, i);
                    
                    //goto the selected line
                    Point p = new Point();
                    p.setLocation(0, i * this.jTableSoC.getRowHeight());
                    this.jScrollPaneSoC.getViewport().setViewPosition(p);
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTableCompareSoCMouseClicked

    private void jTableCompareIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompareIPMouseClicked
        // TODO add your handling code here:
        this.selectedIPIndex = -1;
        System.out.println(this.jTableCompareIP.getName() + ": " + this.jTableCompareIP.getSelectedRow() + " has been selected.");
        this.selectedIPIndex = this.jTableCompareIP.getSelectedRow();
        System.out.println(this.jTableCompareIP.getName() + ": " + this.vIPDataSet.get(selectedIPIndex));
        if(this.selectedIPIndex != -1){
            Vector vSelectedEntry = (Vector) this.vIPDataSet.get(selectedIPIndex);
            for(int i = 0; i < this.jDataSetIP.DataSrc.size(); i++){
                Vector vIter = (Vector) this.jDataSetIP.DataSrc.elementAt(i);
                if (vIter == vSelectedEntry){
                    this.jTableIP.setRowSelectionInterval(i, i);
                    
                    //goto the selected line
                    Point p = new Point();
                    p.setLocation(0, i * this.jTableIP.getRowHeight());
                    this.jScrollPaneIP.getViewport().setViewPosition(p);
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTableCompareIPMouseClicked

    private void jSetTableColWidth(int index, int width, JTable jTableIns){
        TableColumn Column = jTableIns.getColumnModel().getColumn(index);
        Column.setPreferredWidth(width);
        Column.setMaxWidth(width);
        Column.setMinWidth(width);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmhubbubTransCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MmhubbubTransCheckerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartIPAnalyze;
    private javax.swing.JButton StartIPSoCCompare;
    private javax.swing.JButton StartSoCAnalyze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelOutDirIP;
    private javax.swing.JLabel jLabelOutDirSoC;
    private javax.swing.JLabel jLabelScriptIP;
    private javax.swing.JLabel jLabelScriptSoC;
    private javax.swing.JPanel jPanelCompare;
    private javax.swing.JPanel jPanelIP;
    private javax.swing.JPanel jPanelSoC;
    private javax.swing.JScrollPane jScrollPaneCompareIP;
    private javax.swing.JScrollPane jScrollPaneCompareSoC;
    private javax.swing.JScrollPane jScrollPaneIP;
    private javax.swing.JScrollPane jScrollPaneSoC;
    private javax.swing.JTabbedPane jTabbedPaneIP;
    private javax.swing.JTable jTableCompareIP;
    private javax.swing.JTable jTableCompareSoC;
    private javax.swing.JTable jTableIP;
    private javax.swing.JTable jTableSoC;
    private javax.swing.JTextField jTextFieldOutDirIP;
    private javax.swing.JTextField jTextFieldOutDirSoC;
    private javax.swing.JTextField jTextFieldScriptIP;
    private javax.swing.JTextField jTextFieldScriptSoC;
    private javax.swing.JTextField jTextFrameToCompare;
    // End of variables declaration//GEN-END:variables
    private DataSet jDataSetIP;
    private DataSet jDataSetSoC;
    private boolean bIPOpened;
    private boolean bSoCOpened;
    private Vector vIPDataSet;
    private Vector vSoCDataSet;
    private int selectedSoCIndex;
    private int selectedIPIndex;
}
